version: 2

sphinx:
  configuration: docs/conf.py
  fail_on_warning: true

formats:
  - epub
  - pdf

python:
  version: 3.7
  install:
    - requirements: requirements-test.txt
  system_packages: false
